### ISSUE TITLE
Add SocketMobile S550

### ISSUE THREAD

**Issue by LenOttSocketMobile** [reelyactive/sniffypedia#1]
Trying to add SocketMobile S550 Contactless Reader/Writer, but can't push to the gh-pages branch?

**Comment by LenOttSocketMobile** [comment]
When trying to push, I get:
$ git push origin gh-pages
ERROR: Permission to reelyactive/sniffypedia.git denied to LenOttSocketMobile.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


What am i missing?

**Comment by LenOttSocketMobile** [comment]
[SocketMobile_S550.zip](https://github.com/reelyactive/sniffypedia/files/5676359/SocketMobile_S550.zip)

[index.zip](https://github.com/reelyactive/sniffypedia/files/5676360/index.zip)

My updated files are attached.

**Comment by jeffyactive** [comment]
Hi @LenOttSocketMobile, thanks for contributing.  If you make a pull request with the changes, normally we'll approve them (if there are no issues) and merge them into Sniffypedia.  Would you prefer to go that route, or would you prefer I work from the files you attached?  Please advise, thanks!

**Comment by LenOttSocketMobile** [comment]
I tried to do a pull request, but couldn’t get it to work.

I couldn’t seem to push to the gh-pages branch…

I use gitlab a lot, but not github so much

I would be happy to do a push if I can get it to work..


Len

**Comment by jeffyactive** [comment]
If you're willing to give it another shot, fork the repository before you clone, create a new "socketmobile" branch (or equivalent) and then you can complete the pull request.  This should be a good guide if you're less familiar with GitHub: https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

**Comment by LenOttSocketMobile** [comment]
ah, I didn't fork it...let me try that.
I just cloned!

**Comment by LenOttSocketMobile** [comment]
Ok, try now, pull request done!

**Comment by jeffyactive** [comment]
Pull request accepted and merged.

Note that you point the Socket Mobile company code 0x0044 to sniffypedia.org/Organization/Socket_Mobile, but the organization page does not exist (only the product page is included in your pull request).  Do you want to:
- create an index.html for Organization/Socket_Mobile/ or
- embed Schema.org/JSON-LD into www.socketmobile.com and instead point there?

Thanks for contributing to Sniffypedia!

**Comment by LenOttSocketMobile** [comment]
Oops, thanks, missed that!
Would love to do the JSON-LD thing, but for now…
New PR done..

Regards,

Len

**Comment by jeffyactive** [comment]
PR accepted and a sniffypedia@0.1.22 pushed to npm.

Thanks again for the contribution Len!
